cache:
  key: "ruby23"
  paths:
  - vendor

variables:
  RSPEC_RETRY_RETRY_COUNT: "3"

before_script:
  - source ./scripts/prepare_build.sh
  - ruby -v
  - which ruby
  - retry bundle install --path vendor/bundle --without production --jobs $(nproc) "${FLAGS[@]}"
  - bin/rails db:environment:set RAILS_ENV=test
  - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load db:migrate db:seed

stages:
- test

rspec:
  stage: test
  script:
    - RAILS_ENV=test SIMPLECOV=true xvfb-run -a bundle exec rspec
  tags:
    - ruby2.3

bundler:audit:
  stage: test
  only:
    - master
    - staging
  script:
    - "bundle exec bundle-audit update"
    - "bundle exec bundle-audit check"
  tags:
    - ruby2.3
