language: ruby
cache: bundler
script:
  - bundle exec rubocop
  - bundle exec rails db:setup
  - bundle exec rspec spec
  - bundle exec brakeman
  - bundle exec bundle-audit update
  - bundle exec bundle-audit check --ignore CVE-2017-8418
env:
  SMTP_ADDRESS: smtp.example.com
notifications:
  on_success: never
  on_failure: never
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
